micronaut:
  application:
    name: sherlock
  server:
    context-path: /sherlock
    port: 5555
    cors:
      enabled: true
  security:
    authentication: cookie
    redirect:
      login-success: /login/redirect
      login-failure: /login/failure
    oauth2:
      clients:
        orcid:
          client_id: ${ORCID_CLIENT_ID:APP-B1Y73I83LGWWYW26}
          client_secret: ${ORCID_CLIENT_SECRET:9579bd2f-b379-4ff6-9858-dc69a14cfe26}
          scopes: '/authenticate'
          authorization:
            url: 'https://orcid.org/oauth/authorize'
          token:
            url: 'https://orcid.org/oauth/token'
            auth-method: 'client-secret-post'
    token:
      jwt:
        cookie:
          cookie-same-site: none
          cookie-secure: true
          cookie-http-only: false
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:m2hm9T3VdnQK9hGpbarULdDQ5DCZcq30}"'
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:m2hm9T3VdnQK9hGpbarULdDQ5DCZcq30}"'
      refresh:
        cookie:
          cookie-path: /
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        access:
          - isAnonymous()
      - pattern: /redoc/**
        access:
          - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
jena: "${FUSEKI:`http://localhost:3030`}/${DATASET:`iremus`}"
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jackson:
  always-serialize-errors-as-list: false
  mapper:
    ACCEPT_CASE_INSENSITIVE_ENUMS: true
