version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

executors:
  openjdk17:
    docker:
      - image: cimg/openjdk:17.0.1

jobs:
  deploy:
    executor: openjdk17
    steps:
      - checkout
      - run:
          command: ./gradlew dockerBuild


workflows:
  push-sherlock-service:
    jobs:
      - deploy