version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
      - image: dskow/jena-fuseki
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          command: ./gradlew test